version: '3'
services:
  crf-pos:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /usr/app/resources
      - .:/user/app
    command: ["python", "main.py"]